"""init after reset

Revision ID: 031c7452360c
Revises: 
Create Date: 2025-04-21 19:43:41.049404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031c7452360c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('estimate_items_template_id_fkey', 'estimate_items', type_='foreignkey')
    op.drop_constraint('estimate_items_estimate_id_fkey', 'estimate_items', type_='foreignkey')
    op.create_foreign_key(None, 'estimate_items', 'estimates', ['estimate_id'], ['id'])
    op.create_foreign_key(None, 'estimate_items', 'estimate_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimate_items', type_='foreignkey')
    op.drop_constraint(None, 'estimate_items', type_='foreignkey')
    op.create_foreign_key('estimate_items_estimate_id_fkey', 'estimate_items', 'estimates', ['estimate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('estimate_items_template_id_fkey', 'estimate_items', 'estimate_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
