"""Add status to estimates

Revision ID: 05577f7dfb2b
Revises: db12e275e316
Create Date: 2025-05-14 15:06:02.441197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05577f7dfb2b'
down_revision: Union[str, None] = 'db12e275e316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) добавляем колонку в nullable состоянии
    op.add_column(
        "estimates",
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "SENT", "APPROVED", "PAID", "CANCELLED", name="estimate_status"
            ),
            nullable=True,
        ),
    )
    # 2) заполняем все существующие записи значением 'DRAFT'
    op.execute("UPDATE estimates SET status = 'DRAFT' WHERE status IS NULL")
    # 3) делаем колонку NOT NULL
    op.alter_column("estimates", "status", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("estimates", "status")
    sa.Enum(name="estimate_status").drop(op.get_bind(), checkfirst=False)
