"""clients update

Revision ID: 3767bf22bfb5
Revises: d8d2810a4b71
Create Date: 2025-05-02 17:26:44.903125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3767bf22bfb5'
down_revision: Union[str, None] = 'd8d2810a4b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('estimates_client_id_fkey', 'estimates', type_='foreignkey')
    op.create_foreign_key(None, 'estimates', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.create_foreign_key('estimates_client_id_fkey', 'estimates', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
