"""remove vat_enabled from templates

Revision ID: 6d498e0955ac
Revises: 031c7452360c
Create Date: 2025-04-21 23:09:25.160323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d498e0955ac'
down_revision: Union[str, None] = '031c7452360c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimate_templates', 'vat_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate_templates', sa.Column('vat_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
