"""item prices

Revision ID: 9d6aba2a0d49
Revises: c4c7786c8937
Create Date: 2025-05-30 08:54:10.378674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6aba2a0d49'
down_revision: Union[str, None] = 'c4c7786c8937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate_items', sa.Column('internal_price', sa.Float(), nullable=True))
    op.add_column('estimate_items', sa.Column('external_price', sa.Float(), nullable=True))
    op.drop_column('estimate_items', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate_items', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('estimate_items', 'external_price')
    op.drop_column('estimate_items', 'internal_price')
    # ### end Alembic commands ###
