"""init

Revision ID: a0e06fabffd8
Revises: 
Create Date: 2025-05-02 11:56:58.029330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e06fabffd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('estimates', sa.Column('client_company', sa.String(), nullable=True))
    op.add_column('estimates', sa.Column('client_contact', sa.String(), nullable=True))
    op.drop_column('estimates', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('estimates', 'client_contact')
    op.drop_column('estimates', 'client_company')
    op.drop_column('estimates', 'client_name')
    # ### end Alembic commands ###
