"""Make client_id and responsible required, restrict delete

Revision ID: c40dd6217126
Revises: 68bad1b7fa66
Create Date: 2025-05-29 10:58:45.600742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40dd6217126'
down_revision: Union[str, None] = '68bad1b7fa66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimates', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('estimates', 'responsible',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('estimates_client_id_fkey', 'estimates', type_='foreignkey')
    op.create_foreign_key(None, 'estimates', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.create_foreign_key('estimates_client_id_fkey', 'estimates', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.alter_column('estimates', 'responsible',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('estimates', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
