"""«n

Revision ID: c4c7786c8937
Revises: c40dd6217126
Create Date: 2025-05-29 14:31:22.627930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c7786c8937'
down_revision: Union[str, None] = 'c40dd6217126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('legal_address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('actual_address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('kpp', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bik', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('account', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bank', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('corr_account', sa.String(), nullable=True))
    op.drop_column('clients', 'address')
    op.add_column('estimates', sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('estimates', sa.Column('event_place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'event_place')
    op.drop_column('estimates', 'event_datetime')
    op.add_column('clients', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'corr_account')
    op.drop_column('clients', 'bank')
    op.drop_column('clients', 'account')
    op.drop_column('clients', 'bik')
    op.drop_column('clients', 'kpp')
    op.drop_column('clients', 'inn')
    op.drop_column('clients', 'actual_address')
    op.drop_column('clients', 'legal_address')
    # ### end Alembic commands ###
