"""clients

Revision ID: d8d2810a4b71
Revises: a0e06fabffd8
Create Date: 2025-05-02 13:05:28.907936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d2810a4b71'
down_revision: Union[str, None] = 'a0e06fabffd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estimates', 'clients', ['client_id'], ['id'])
    op.drop_column('estimates', 'client_company')
    op.drop_column('estimates', 'client_contact')
    op.drop_column('estimates', 'client_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('estimates', sa.Column('client_contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('estimates', sa.Column('client_company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.drop_column('estimates', 'client_id')
    # ### end Alembic commands ###
