"""make estimate client nullable

Revision ID: fb212cb36ab6
Revises: f935bf534933
Create Date: 2025-06-17 10:20:12.498157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb212cb36ab6'
down_revision: Union[str, None] = 'f935bf534933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_change_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('estimates', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimates', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_change_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
